version: '3'

services:
  bot:
    build: .
    volumes:
      - ./data:/data
    environment:
      URL: "CHANGEME"
      TELEGRAM_BOT_TOKEN: "CHANGEME"
      TELEGRAM_CHAT_ID: "CHANGEME"
      POLL_INTERVAL: "3600"
